"""
Django settings for fundi_backend project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if os.getenv('DEBUG', 'True').lower() in {'1', 'true', 'yes', 'on'}:
        # Development only - insecure fallback
        SECRET_KEY = 'django-insecure-dev-only-local-testing-do-not-use-in-production'
    else:
        raise ValueError(
            'SECRET_KEY environment variable is required in production. '
            'Generate one with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"'
        )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '[::1]',
    'myfundihubfront.up.railway.app',
    'myfundihubback.up.railway.app',
    'myfundihubfront-production.up.railway.app',
    'myfundihubback-production.up.railway.app',
]
railway_domain = os.getenv('RAILWAY_PUBLIC_DOMAIN')
if railway_domain:
    ALLOWED_HOSTS.append(railway_domain)

CORS_ALLOWED_ORIGINS = [
    'https://myfundihubfront.up.railway.app',
    'https://myfundihubback.up.railway.app',
    'https://myfundihubfront-production.up.railway.app',
    'https://myfundihubback-production.up.railway.app',
]
if railway_domain:
    CORS_ALLOWED_ORIGINS.append(f'https://{railway_domain}')
    CORS_ALLOWED_ORIGINS.append(f'http://{railway_domain}')
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ['*']
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'fundi_backend.middleware.allow_railway_origin',
]

ROOT_URLCONF = 'fundi_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fundi_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL') or os.getenv('PGDATABASE_URL') or os.getenv('POSTGRES_URL')

# Prefer Railway's supplied database URL first.
if DATABASE_URL:
    parsed_db = dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    if 'railway.internal' in DATABASE_URL or 'postgres' in DATABASE_URL:
        parsed_db.setdefault('OPTIONS', {})['sslmode'] = 'require'
    DATABASES = {
        'default': parsed_db,
    }
# Fallback to the explicit PostgreSQL variables you shared.
elif os.getenv('PGHOST') or os.getenv('POSTGRES_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('PGDATABASE') or os.getenv('POSTGRES_DB', 'railway'),
            'USER': os.getenv('PGUSER') or os.getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.getenv('PGPASSWORD') or os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('PGHOST') or os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('PGPORT') or os.getenv('POSTGRES_PORT', '5432'),
        }
    }
else:
    # Local fallback used only when no database URL is available.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Email settings
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Validate email credentials in production
if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    if not DEBUG:
        raise ValueError(
            'EMAIL_HOST_USER and EMAIL_HOST_PASSWORD environment variables are required in production'
        )
    # In DEBUG mode, allow empty email config (for testing)
    EMAIL_HOST_USER = EMAIL_HOST_USER or 'noemail@test.local'
    EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD or 'test'

if not DEFAULT_FROM_EMAIL:
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# Cache Configuration for Rate Limiting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 10000,
        }
    }
}

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Security Settings
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_SECURITY_POLICY = {
    'default-src': ("'self'",),
}

# Admin Registration Key - must be set in production
ADMIN_REGISTRATION_KEY = os.getenv('ADMIN_REGISTRATION_KEY')
if not ADMIN_REGISTRATION_KEY:
    if not DEBUG:
        raise ValueError(
            'ADMIN_REGISTRATION_KEY environment variable is required in production'
        )
    # Development only
    ADMIN_REGISTRATION_KEY = 'dev-admin-key-local-only'

# Paystack Payment Configuration
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY')
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')

if not PAYSTACK_PUBLIC_KEY or not PAYSTACK_SECRET_KEY:
    if not DEBUG:
        raise ValueError(
            'PAYSTACK_PUBLIC_KEY and PAYSTACK_SECRET_KEY environment variables are required in production'
        )
    # Development only - test keys (these don't work for real transactions)
    PAYSTACK_PUBLIC_KEY = 'pk_test_dev_key'
    PAYSTACK_SECRET_KEY = 'sk_test_dev_key'

# Frontend URL for payment callbacks
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'security': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': 'WARNING',
        },
    },
    'loggers': {
        'api': {
            'handlers': ['console'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

