from django.urls import path
from .views import (
    bookings_view,
    forgot_password_view,
    login_view,
    register_view,
    admin_register_view,
    reset_password_view,
    user_view,
    admin_users_view,
    menu_view,
    customer_dashboard_view,
    admin_dashboard_view,
    technician_dashboard_view,
    technicians_view,
    assign_booking_view,
    verify_reset_code_view,
)
from .payment_views import (
    initialize_payment_view,
    verify_payment_view,
    paystack_callback_view,
    payment_status_view,
    payment_history_view,
    refund_payment_view,
    paystack_webhook_view,
    user_payments_view,
)

urlpatterns = [
    path('auth/login/', login_view, name='login'),
    path('auth/register/', register_view, name='register'),
    path('auth/admin-register/', admin_register_view, name='admin-register'),
    path('auth/forgot-password/', forgot_password_view, name='forgot-password'),
    path('auth/verify-reset-code/', verify_reset_code_view, name='verify-reset-code'),
    path('auth/reset-password/', reset_password_view, name='reset-password'),
    path('bookings/', bookings_view, name='bookings'),
    path('bookings/assign/', assign_booking_view, name='assign-booking'),
    path('technicians/', technicians_view, name='technicians'),
    path('user/', user_view, name='user'),
    path('admin/users/', admin_users_view, name='admin-users'),
    path('menu/', menu_view, name='menu'),
    path('dashboard/customer/', customer_dashboard_view, name='customer-dashboard'),
    path('dashboard/admin/', admin_dashboard_view, name='admin-dashboard'),
    path('dashboard/technician/', technician_dashboard_view, name='technician-dashboard'),
    
    # Payment endpoints
    path('payments/initialize/', initialize_payment_view, name='initialize-payment'),
    path('payments/verify/<str:reference>/', verify_payment_view, name='verify-payment'),
    path('payments/callback/<str:reference>/', paystack_callback_view, name='paystack-callback'),
    path('payments/<int:payment_id>/status/', payment_status_view, name='payment-status'),
    path('payments/list/', user_payments_view, name='user-payments'),
    path('payments/history/', payment_history_view, name='payment-history'),
    path('payments/<int:payment_id>/refund/', refund_payment_view, name='refund-payment'),
    path('payments/webhook/paystack/', paystack_webhook_view, name='paystack-webhook'),
]
